version: '3'

services:
  api:
    build:
      context: ./api
    container_name: sosaa-api
    depends_on:
      - db
    environment:
      DATABASE_URL: ${DATABASE_URL}
    restart: 'unless-stopped'

  frontend:
    build:
      context: ./client
    container_name: sosaa-frontend
    restart: 'unless-stopped'

  db:
    image: postgres
    container_name: sosaa-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

networks:
  sosaa-network:
  nginx-proxy-manager_default:
    external: true
