version: '3'

services:
  api:
    build:
      context: ./api
    depends_on:
      - db
    environment:
      DATABASE_URL: ${DATABASE_URL}
    restart: 'unless-stopped'

  frontend:
    build:
      context: ./client
    restart: 'unless-stopped'

  db:
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

networks:
  default:
    external: true
    name: nginx-proxy-manager_default
